export const USERS_LIST_REQUEST = 'USERS_LIST_REQUEST';
export const USERS_LIST_SUCCESS = 'USERS_LIST_SUCCESS';
export const USERS_LIST_FAIL = 'USERS_LIST_FAIL';

export const LOAD_MORE_USERS_REQUEST = 'LOAD_MORE_USERS_REQUEST';
export const LOAD_MORE_USERS_SUCCESS = 'LOAD_MORE_USERS_SUCCESS';
export const LOAD_MORE_USERS_FAIL = 'LOAD_MORE_USERS_FAIL';

export const LOAD_SINGLE_USER_REQUEST = 'LOAD_SINGLE_USER_REQUEST';
export const LOAD_SINGLE_USER_SUCCESS = 'LOAD_SINGLE_USER_SUCCESS';
export const LOAD_SINGLE_USER_FAIL = 'LOAD_SINGLE_USER_FAIL';

export const ADD_NEW_USER_PAGE = 'ADD_NEW_USER_PAGE';
export const SINGLE_USER_PAGE = 'SINGLE_USER_PAGE';
export const ALL_USERS_PAGE = 'ALL_USERS_PAGE';

export const TEXT_FIELD_ERROR = 'TEXT_FIELD_ERROR';
export const AGE_ERROR = 'AGE_ERROR';
export const RESET_ERRORS = 'RESET_ERRORS';
export const ALL_GOOD = 'ALL_GOOD';

export const ID = 'ID';
export const NAME = 'NAME';
export const SURNAME = 'SURNAME';
export const EMAIL = 'EMAIL';
export const BIRTH_DATE = 'BIRTH_DATE';
export const OCCUPATION = 'OCCUPATION';
